routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */


$languages = array('ar', 'en', 'fr');
$defaultLanguage = 'ar';
if ($defaultLanguage) {
    $defaultLanguageCode = $defaultLanguage;
} else {
    $defaultLanguageCode = 'ar';
}

$currentLanguageCode = Request::segment(1, $defaultLanguageCode);
if (in_array($currentLanguageCode, $languages)) {
    Route::get('/', function () use($defaultLanguageCode) {
        return redirect()->to($defaultLanguageCode);
    });

 
    Route::group(['namespace' => 'Front', 'prefix' => $currentLanguageCode], function () use($currentLanguageCode) {
        app()->setLocale($currentLanguageCode);
        Route::get('/', 'HomeController@index')->name('home');
        Route::get('getRegionByCity/{id}', 'AjaxController@getRegionByCity');
        Route::get('getAddress/{id}', 'AjaxController@getAddress');
        Route::post('location-suggestions', 'AjaxController@search');
        Route::post('change-location', 'AjaxController@changeLocation');
        Route::get('meal-choices', 'AjaxController@getMealOrSizeChoices');
        Auth::routes();

        Route::get('user-activation-code', 'Auth\RegisterController@showActivationForm')->name('activation');
        Route::post('activateuser', 'Auth\RegisterController@activate_user')->name('activationuser');

        Route::get('edit-user-phone', 'Auth\RegisterController@showEditMobileForm')->name('edit-phone');
        Route::post('edituserphone', 'Auth\RegisterController@EditPhone')->name('editphone');

        Route::get('login/facebook', 'Auth\RegisterController@redirectToProvider')->name('login/facebook');
        Route::get('login/facebook/callback', 'Auth\RegisterController@handleProviderCallback');
        
        Route::get('complete-registeration', 'Auth\RegisterController@showCompleteRegistrationForm')->name('complete_register');
        

        Route::get('about-us', 'StaticController@about_us')->name('about_us');
        Route::get('usage-and-conditions', 'StaticController@usage_coditions')->name('usage_conditions');
        Route::get('terms-and-conditions', 'StaticController@terms_conditions')->name('terms_conditions');
        Route::get('contact-us', 'StaticController@contact_us')->name('contact_us');
        Route::get('offers', 'StaticController@offers')->name('offers');
        Route::post('contact_us', 'StaticController@sendContactMessage')->name('contact');
       
        Route::get('cart', 'CartController@index')->name('showcart');
        Route::get('cart/empty', 'CartController@emptyCart');
        Route::post('cart', 'CartController@store');
        Route::get('resend_order', 'CartController@resendOrder')->name('resend_order');
        Route::get('cart/{index}/remove', 'CartController@remove');
        Route::get('cart/update-quantity', 'CartController@update_quantity');
        Route::get('cart/coupon-check', 'CartController@coupon_check');
        Route::post('cart/new-order', 'CartController@new_order');
        Route::get('resturantes', 'ResturantesController@index')->name('show_resturantes');
        Route::get('near_me', 'ResturantesController@getMyLocation')->name('near_me');
        
        Route::get('resturant/{resturant}', 'ResturantesController@resturant');
        Route::get('resturant/{resturant}/info', 'ResturantesController@resturant_info')->name('resturant_info');
        Route::get('resturant/{resturant}/{menu_section}', 'ResturantesController@menu');
        Route::get('resturant/{resturant}/{menu_section}/{meal}', 'ResturantesController@meal');
        Route::get('resturantes/cuisines/{cuisine}', 'ResturantesController@getResturantesByCuisine');
        Route::post('resturantes/suggest', 'ResturantesController@suggest');
        /*************************** user ***************/
        Route::get('user-profile','UsersController@profile')->name('profile');
        Route::get('edit-user-profile','UsersController@editProfile')->name('edit_profile');
        Route::post('update-user','UsersController@updateProfile')->name('update_user');
        Route::get('add-favourite','UsersController@addDeleteFavourite')->name('add-favourite');
        Route::get('user-favourites','UsersController@favourites')->name('user-favourites');

        /*************************** addresses ************/
        Route::resource('user-addresses', 'AddressesController');
        
        Route::get('delete-addresses/{id}', 'AddressesController@destroy')->name('delete-address');

        /********************** orders *****************/
        Route::resource('user-orders', 'OrdersController');
        Route::post('rate-order', 'OrdersController@rate')->name('rate_order');
        Route::get('order-meal/update-quantity', 'OrdersController@updateOrderMealQuantity');
        Route::get('order-meal/remove', 'OrdersController@removeOrderMeal');
        
        

    });
} else {
    Route::get('/' . $currentLanguageCode, function () use($defaultLanguageCode) {
        return redirect()->to($defaultLanguageCode);
    });
}


//Route::group(['middleware'=>'auth:admin'], function () {
Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function () {
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/error', 'AdminController@error')->name('admin.error');
    Route::get('/change_lang', 'AjaxController@change_lang')->name('ajax.change_lang');
    Route::get('/getRegionByCity/{id}', 'AjaxController@getRegionByCity')->name('ajax.getRegionByCity');
    Route::get('/getResturantBranches/{id}', 'AjaxController@getResturantBranches')->name('ajax.getResturantBranches');
    Route::get('getMenueSectionsByResturant/{id}', 'AjaxController@getMenueSectionsByResturant');
    Route::post('notify', 'AjaxController@notify');
    Route::post('send_email', 'AjaxController@send_email');
    Route::get('getToppings', 'AjaxController@getToppings');
    Route::get('getSizes', 'AjaxController@getSizes');

     Route::get('profile', 'ProfileController@index');
    Route::patch('profile', 'ProfileController@update');



    Route::resource('groups', 'GroupsController');
    Route::resource('admins', 'AdminsController');
    Route::resource('users', 'UsersController');
    Route::resource('categories', 'CategoriesController');
    Route::resource('cities', 'CitiesController');
    Route::resource('sizes', 'SizesController');
    Route::resource('offers', 'OffersController');
    Route::resource('cuisines', 'CuisinesController');
    Route::resource('coupons', 'CouponsController');
    Route::resource('toppings', 'ToppingsController');
    Route::resource('choices', 'ChoicesController');
    Route::resource('sub_choices', 'SubChoicesController');
    Route::resource('meal_sizes', 'MealSizesController');
    Route::resource('resturantes', 'ResturantesController');
    Route::resource('resturant_branches', 'ResturantBranchesController');
    Route::resource('menu_sections', 'MenuSectionsController');
    Route::resource('slider', 'SliderController');
    Route::delete('menu_sections/{id}/toppings', 'MenuSectionsController@destroy_topping');
    Route::resource('meals', 'MealsController');
    Route::delete('meals/{id}/sizes', 'MealsController@destroy_size');
    Route::delete('meals/{id}/toppings', 'MealsController@destroy_topping');
    Route::resource('contact_messages', 'ContactMessagesController');
    Route::resource('recommendations', 'RecommendationsController');
    Route::resource('ads', 'AdsController');
    Route::resource('orders_reports', 'OrdersReportsController');
    Route::post('orders_reports/download', 'OrdersReportsController@download');
    Route::get('settings', 'SettingsController@index');
    Route::get('resturant_menu', 'ResturantMenuController@index');
    Route::get('resturant_meals', 'ResturantMealsController@index');
    Route::get('resturant_meals/{id}', 'ResturantMealsController@show');
    Route::get('resturant_meals/status/{id}', 'ResturantMealsController@status');
    Route::get('resturant_orders', 'ResturantOrdersController@index');
    Route::get('resturant_orders/{id}', 'ResturantOrdersController@show');
    Route::post('change_order_status', 'ResturantOrdersController@changeStatus')->name('order_status');





    Route::patch('settings/{id}', 'SettingsController@update');
    Route::get('notifications', 'NotificationsController@index');
    Route::post('notifications', 'NotificationsController@store');




    Route::post('groups/data', 'GroupsController@data');

    Route::post('admins/data', 'AdminsController@data');
    Route::post('users/data', 'UsersController@data');
    Route::get('users/status/{id}', 'UsersController@status');

    Route::post('contact_messages/data', 'ContactMessagesController@data');
    Route::post('ads/data', 'AdsController@data');
    Route::post('categories/data', 'CategoriesController@data');
    Route::post('cities/data', 'CitiesController@data');
    Route::post('sizes/data', 'SizesController@data');
    Route::post('toppings/data', 'ToppingsController@data');
    Route::post('choices/data', 'ChoicesController@data');
    Route::post('sub_choices/data', 'SubChoicesController@data');
    Route::post('cuisines/data', 'CuisinesController@data');
    Route::post('resturantes/data', 'ResturantesController@data');
    Route::post('resturant_branches/data', 'ResturantBranchesController@data');
    Route::post('menu_sections/data', 'MenuSectionsController@data');
    Route::post('resturant_menu/data', 'ResturantMenuController@data');
    Route::post('resturant_meals/data', 'ResturantMealsController@data');
    Route::post('resturant_orders/data', 'ResturantOrdersController@data');

app/Http/Controllers/Front/AddressesController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\FrontController;
use Validator;
use App\Models\Address;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Contracts\Encryption\DecryptException;

class AddressesController extends FrontController
{
    private $rules = array(
        'city' => 'required',
        'region' => 'required',
        'sub_region' => 'required',
        'street' => 'required',
        'building_number' => 'required',
        'floor_number' => 'required',
        'apartment_number' => 'required',
    );

    public function __construct() {
        parent::__construct();
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->data['page_title'] = _lang('app.addresses');
        try {
            $addresses = Address::where('user_id',$this->User->id)
                                  ->paginate($this->limit);
            $this->data['addresses'] = $addresses;
            return $this->_view('addresses.index');
        } catch (\Exception $e) {
            session()->flash('msg',_lang('app.error_is_occured_try_again_later'));
            return redirect()->back();
        }
    }

    public function create()
    {
        $this->data['page_title'] = _lang('app.add_address');
        return $this->_view('addresses.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $validator = Validator::make($request->all(), $this->rules);
            if ($validator->fails()) {

                if ($request->ajax()) {
                    $errors = $validator->errors()->toArray();
                    return _json('error',$errors);
                } else {
                    return redirect()->back()->withInput()->withErrors($validator->errors()->toArray());
                }
            }
           
            $address = new Address;
            $address->city = $request->city;
            $address->region = $request->region;
            $address->sub_region = $request->sub_region;
            $address->street = $request->street;
            $address->building_number = $request->building_number;
            $address->floor_number = $request->floor_number;
            $address->apartment_number = $request->apartment_number;
            if ($request->special_sign) {
                $address->special_sign = $request->special_sign;
            }
            else{
                $address->special_sign = "";
            }
            if ($request->extra_info) {
                $address->extra_info = $request->extra_info;
            }
            else{
                $address->extra_info = "";
            }
            $address->user_id = $this->User->id;
            $address->save();
           
            session()->flash('msg',_lang('app.added_successfully'));
            if($request->return){
                $url = url(base64_decode($request->return));
            }else{
                $url=_url('user-addresses');
            }
            //dd($url);
            if ($request->ajax()) {
                
               return _json('success',$url);
           } 
           return redirect($url);

        } catch (\Exception $e) {
            session()->flash('msg',_lang('app.error_is_occured_try_again_later'));
            return redirect()->back();
        }
    }

    public function edit($id)
    {
        $this->data['page_title'] = _lang('app.edit_address');
        $address_id = decrypt($id);
        $address = Address::where('id',$address_id)->where('user_id',$this->User->id)->first();
        if (!$address) {
            return $this->err404();
        }
        $this->data['address'] = $address;
        return $this->_view('addresses.edit');
    }
   
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $address_id = decrypt($id);
            $address = Address::where('id',$address_id)->where('user_id',$this->User->id)->first();
            if (!$address) {
                return $this->err404();
            }
            $validator = Validator::make($request->all(), $this->rules);
            if ($validator->fails()) {

                if ($request->ajax()) {
                    $errors = $validator->errors()->toArray();
                    return _json('error',$errors);
                } else {
                    return redirect()->back()->withInput()->withErrors($validator->errors()->toArray());
                }
            }
           
            $address->city = $request->city;
            $address->region = $request->region;
            $address->sub_region = $request->sub_region;
            $address->street = $request->street;
            $address->building_number = $request->building_number;
            $address->floor_number = $request->floor_number;
            $address->apartment_number = $request->apartment_number;
            if ($request->special_sign) {
                $address->special_sign = $request->special_sign;
            }
            if ($request->extra_info) {
                $address->extra_info = $request->extra_info;
            }
            $address->save();
            session()->flash('msg',_lang('app.updated_successfully'));

            if ($request->ajax()) {
               return _json('success',route('user-addresses.index'));
           } 
           return redirect()->route('user-addresses.index');

        } catch (\Exception $e) {
            session()->flash('msg',_lang('app.error_is_occured_try_again_later'));
            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $address_id = decrypt($id);
            $address = Address::where('id',$address_id)->where('user_id',$this->User->id)->first();
            if (!$address) {
                return $this->err404();
            }
            $address->delete();
            session()->flash('msg',_lang('app.deleted_successfully'));
           return redirect()->route('user-addresses.index');
        } catch (\Exception $e) {
            session()->flash('msg',_lang('app.error_is_occured_try_again_later'));
            return redirect()->back();
        }
    }
}

resources/views/main_content/front/orders/completed.blade.php
@extends('layouts.user_profile')
@section('pageTitle',$page_title)

@section('title')
{{ $page_title }}
@endsection
@section('js')

<script type="text/javascript" src="{{url('public/front/js')}}/jquery.jscroll.js"></script>

<script type="text/javascript">
    $('ul.pagination').hide();
    $(function () {
        $('.infinite-scroll').jscroll({
            autoTrigger: true,
            loadingHtml: '<img class="center-block" style="margin-left:35%;" src="{{url('public/front')}}/images/loading.gif" alt="Loading..." />',
            padding: 0,
            nextSelector: '.pagination li.active + li a',
            contentSelector: 'div.infinite-scroll',
            callback: function () {
                $('ul.pagination').remove();
            }
        });
    });
</script>

@endsection

@section('content')
<div class="col-sm-12 float-menu">

  <div class="request-responsive" style="margin-top: 40px;">
    
    <div class="infinite-scroll">
    @foreach ($orders as $order)
    
    <div class="bordlin">
      <a href="{{route('user-orders.show',Crypt::encrypt($order->id))}}">
      <div class="centers">
        <div href="#" class="imgover">
         <img src="{{ $order->resturant_image }}"> 
       </div>
     </div>
     <div class="divtitle">
       <h3 class="nam-tit">{{ $order->resturant }} - {{ $order->region }}</h3>
       <span class="textdeit"><i class="fa fa-calendar" aria-hidden="true"></i> {{ $order->date }} </span>
     </div>
     </a>
   </div>
   
   @endforeach
   {{ $orders->appends($_GET)->links() }} 
</div>


</div>
</div>

@endsection

resources/views/main_content/front/orders/current.blade.php
@extends('layouts.user_profile')
@section('pageTitle',$page_title)

@section('title')
{{ $page_title }}
@endsection


@section('js')

<script type="text/javascript" src="{{url('public/front/js')}}/jquery.jscroll.js"></script>

<script type="text/javascript">
    $('ul.pagination').hide();
    $(function () {
        $('.infinite-scroll').jscroll({
            autoTrigger: true,
            loadingHtml: '<img class="center-block" style="margin-left:35%;" src="{{url('public/front')}}/images/loading.gif" alt="Loading..." />',
            padding: 0,
            nextSelector: '.pagination li.active + li a',
            contentSelector: 'div.infinite-scroll',
            callback: function () {
                $('ul.pagination').remove();
            }
        });
    });
</script>

@endsection

@section('content')

<div class="col-sm-12 float-menu">

    <div class="request-responsive" style="margin-top: 40px;">
      <div class="infinite-scroll">
      @foreach ($orders as $order)
      
      <div class="bordlin">
         <a href="{{route('user-orders.show',Crypt::encrypt($order->id))}}">
        <div class="centers">
          <div href="#" class="imgover">
           <img src="{{ $order->resturant_image }}"> 
         </div>
       </div>
       <div class="divtitle">
        <h3 class="nam-tit">{{ $order->resturant }} - {{ $order->region }}</h3>
         <span class="namber">{{ $order->status_text }}</span> </div>
          </a>
       </div>
       
       @endforeach
           {{ $orders->appends($_GET)->links() }} 
     </div>

       
    </div>
  
</div>




@endsection

resources/views/main_content/front/orders/edit.blade.php
@extends('layouts.user_profile')

@section('pageTitle','Ga3aaan')
@section('title')
{{ _lang('app.edit_order') }}
@endsection

@section('js')
<script src=" {{ url('public/front/scripts') }}/orders.js"></script>


@endsection



@section('content')


<div class="alert alert-success" style="display:{{Session('successMessage')?'block;':'none;'}}; " role="alert"><i class="fa fa-check" aria-hidden="true"></i> <span class="message">{{Session::get('successMessage')}}</span></div>
<div class="alert alert-danger" style="display:{{Session('errorMessage')?'block;':'none;'}}; " role="alert"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> <span class="message">{{Session::get('errorMessage')}}</span></div>
<div id="loader" style="z-index:9999;display:none;"></div>
<div class="col-md-12" id="cart-content">
    <div class="orderbasc">
        <ul class="nameprofile basket">
            <li class="basket-det">
                @foreach($order_meals as $one)
                <div class="row item-row">
                    <div class="top col-sm-10 size">
                        <div class="input-group" style="margin:0 0 0 15px;width: 120px;"> <span class="input-group-btn">
                                <button type="button" class="btn btn-default btn-number btn-qty-plus"   data-type="plus" data-id="{{$one->id}}" data-field="qty[{{$one->id}}]"> <span class="glyphicon glyphicon-plus"></span> </button>
                            </span>
                            <input name="qty[{{$one->id}}]" class="form-control input-number" value="{{$one->quantity}}" min="1" max="10" type="text">
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-default btn-number btn-qty-minus" data-type="minus" data-id="{{$one->id}}" data-field="qty[{{$one->id}}]" disabled="disabled"> <span class="glyphicon glyphicon-minus"></span> </button>
                            </span>
                        </div>
                        <p>{{$one->meal_title}}</p>

                    </div>
                    @foreach($one->toppings as $topping)
                    <div class="bottom col-sm-10">
                        <p style="font-size:14px; color:#656565;">{{$topping->title}}</p>
                    </div>
                    @endforeach
                    <i class="fa fa-times remove-cart" aria-hidden="true" data-id="{{$one->id}}" id="hide" style="float:left; font-size:22px; cursor: pointer;padding-left:10px; color:#d5344a;"></i>

                </div>
                @endforeach
            </li>
        </ul>
    </div>
    <!--orderbasc-->

    <div class="orderbasc">

        <ul class="nameprofile basket addtext">
            <li>
                <p class="sizcolo">السعر الاساسى</p>
                <p class="deyleft" id="primary_price"> {{$order->primary_price.' '.$currency_sign}}</p>
            </li>
            <li>
                <p class="sizcolo">رسوم الخدمة</p>
                <p class="deyleft"> {{$order->service_charge}}  </p>
            </li>
            <li>
                <p class="sizcolo">قيمة الضريبة المضافة</p>

                <p class="deyleft"> {{$order->vat}}  </p>
            </li>
            <li>
                <p class="sizcolo">رسوم خدمة التوصيل</p>
                <p class="deyleft"> {{$order->delivery_cost.' '.$currency_sign}}  </p>
            </li>
        </ul>

    </div>
    <ul class="nameprofile basket">
        @if ($order->coupon)
        <li>
            <p>{{ _lang('app.coupon') }}</p>
            <br>
            <p>{{ $order->coupon }}</p>
        </li>
        @endif

        <li>
            <p>{{ _lang('app.address') }}</p>
            <br>
            <p>{{ $order->city }},{{ $order->region }} ,{{ $order->sub_region }},  {{ $order->building_number }} {{ $order->street }}</p>
        </li>
    </ul>
    <div class="total">
        <p>المجموع</p>
        <p id="total_price">{{ $order->total_cost }} {{ $currency_sign }}</p>
    </div>
    <!--total-->

</div>
<div id="requestMessageModal" class="modal fade in" role="dialog" aria-hidden="false" >
        <div class="modal-dialog"> 

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="btn btn-default cols" data-dismiss="modal">×</button>
                    <h4 class="modal-title titlpop">رسالة</h4>
                </div>
                <div class="modal-body">
                    <p class="text-center bothenk">تم مسح طلبك</p>
                </div>
            </div>
        </div>
    </div>
    <!--myModa2--> 


<script>
var new_config = {

}
</script>



@endsection

resources/views/main_content/front/orders/show.blade.php
@extends('layouts.user_profile')
@section('pageTitle',$page_title)

@section('title')
{{ $page_title }}
@endsection

@section('js')
<script src=" {{ url('public/front/scripts') }}/orders.js"></script>
@endsection

@section('content')

<div class="alert alert-success" style="display:{{Session('successMessage')?'block;':'none;'}}; " role="alert"><i class="fa fa-check" aria-hidden="true"></i> <span class="message">{{Session::get('successMessage')}}</span></div>
<div class="alert alert-danger" style="display:{{Session('errorMessage')?'block;':'none;'}}; " role="alert"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> <span class="message">{{Session::get('errorMessage')}}</span></div>
@if($minutes<$order_minutes_limit && $order->status==1)
<div class="centernamber" id="countdown">
    <div class="naminner countdown"></div>
    <!--naminner-->

    <p class="textinner">الوقت المتبقى للتعديل على الطلب</p>
    <a href="{{_url('user-orders/'.encrypt($order->order_id).'/edit')}}" class="botoom addadrs basket ">تعديل</a>
    <a href="#" data-id="{{encrypt($order->order_id)}}" class="botoom addadrs basket" onclick="Orders.delete(this);return false;">الغاء</a> 
</div>
@endif
<div class="orderbasc">
    <ul class="nameprofile basket">
        @foreach ($order_meals as $order_meal)

        <li>
            <p class="rad">{{ $order_meal->quantity }} X</p>
            <p>{{ $order_meal->size_title }} -  {{ $order_meal->meal_title }}</p>
            
            <p class="deyleft"> {{ $order_meal->cost_of_meal+$order_meal->sub_choices_price }} {{ $currency_sign }} </p>
            <div class="clearfix"></div>
            @foreach($order_meal->sub_choices as $choice)
            <p>{{$choice->$title_slug}}</p>
            <div class="clearfix"></div>
            @endforeach
        </li>

        @endforeach


    </ul>
</div>
<!--orderbasc-->

<ul class="nameprofile basket addtext nemerg">
    <li>
        <p class="sizcolo">{{ _lang('app.primary_price') }}</p>
        <p class="deyleft"> {{ $order->primary_price }} {{ $currency_sign }} </p>
    </li>

    <li>
        <p class="sizcolo">{{ _lang('app.service_charge') }}</p>
        <p class="deyleft">  {{ $order->service_charge }} % </p>
    </li>
    <li>
        <p class="sizcolo">{{ _lang('app.vat') }}</p>
        <p class="deyleft">  {{ $order->vat }} % </p>
    </li>
    <li>
        <p class="sizcolo">{{ _lang('app.delivery_cost') }}</p>
        <p class="deyleft"> {{ $order->delivery_cost }} {{ $currency_sign }} </p>
    </li>
</ul>

<!--nameprofile-->

<ul class="nameprofile basket">
    @if ($order->coupon)
    <li>
        <p>{{ _lang('app.coupon') }}</p>
        <br>
        <p>{{ $order->coupon }}</p>
    </li>
    @endif

    <li>
        <p>{{ _lang('app.address') }}</p>
        <br>
        <p>{{ $order->city }},{{ $order->region }} ,{{ $order->sub_region }},  {{ $order->building_number }} {{ $order->street }}</p>
    </li>
</ul>
<div class="total">
    <p>{{ _lang('app.total') }}</p>
    <p>{{ $order->net_cost }} {{ $currency_sign }}</p>
</div>
<!--total-->

<div class="steps"> 

    <a href="" class="righton {{ $order->status == 1 || $order->status == 2 || $order->status == 3 ? 'active' : '' }}"> 
        <img src="{{ url('public/front') }}/images/hand.png">
        <i class="fa fa-circle" aria-hidden="true"></i>
        <p>جارى تجهيز الطلب</p>
    </a> <!--righton--> 

    <a href="" class="righton centerblok {{  $order->status == 2 || $order->status == 3 ? 'active' : '' }}"> <img src="{{ url('public/front') }}/images/order.png"> <i class="fa fa-circle" aria-hidden="true"></i>
        <p>جارى توصيل الطلب</p>
    </a> <!--righton--> 

    <a href="" class="righton leftbox {{ $order->status == 3 ? 'active' : '' }}"> <img src="{{ url('public/front') }}/images/den.png"> <i class="fa fa-circle" aria-hidden="true"></i>
        <p>تم توصيل الطلب</p>
    </a> <!--righton--> 

</div>
@if ($order->status == 3)
<div class="row">

    @if ($order->is_rated == 0)
    <div class="col-md-6 col-xs-6">
        <a href="#myModa2" data-toggle="modal" class="botoom">{{ _lang('app.rate_order') }}</a>
    </div>
    @endif
    <div class="col-md-6 col-xs-6">
        <a href="{{ route('resend_order') }}?resturant_id={{ $order->resturant_id }}&order_id={{ $order->order_id }}" data-order="" data-resturant="" class="botoom">{{ _lang('app.resend_order') }}</a>
    </div>


    @endif
</div>

<div id="myModa2" class="modal fade in" role="dialog" aria-hidden="false">
    <div class="modal-dialog"> 

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn btn-default cols" data-dismiss="modal">×</button>
                <h4 class="modal-title titlpop">{{ _lang('app.rate_order') }}</h4>
            </div>
            <div class="modal-body nonepad">
                <form action="{{ route('rate_order') }}" method="POST" role="form" class="form-search">
                    {{ csrf_field() }}
                    <div class="row"> 
                        <input type="hidden" name="order_id" value="{{ Crypt::encrypt($order->order_id) }}">
                        <input class="rating-input" name="rate" type="text" title="" required />
                        <div class="col-sm-12 inputbox">
                            <textarea class="form-control textarea" name="opinion" placeholder="{{ _lang('app.opinion') }}"></textarea>
                        </div>
                        <div class="col-sm-12 inputbox merges">
                            <button type="submit" class="botoom">{{ _lang('app.save') }}</button>
                        </div>
                    </div>
                    <!--row-->

                </form>
            </div>
        </div>
    </div>
</div>

<script>
    var new_config = {
        minutes: '{{$minutes}}',
        order_minutes_limit: '{{$order_minutes_limit }}',
    }
</script>
@endsection