routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */


$languages = array('ar', 'en', 'fr');
$defaultLanguage = 'ar';
if ($defaultLanguage) {
    $defaultLanguageCode = $defaultLanguage;
} else {
    $defaultLanguageCode = 'ar';
}

$currentLanguageCode = Request::segment(1, $defaultLanguageCode);
if (in_array($currentLanguageCode, $languages)) {
    Route::get('/', function () use($defaultLanguageCode) {
        return redirect()->to($defaultLanguageCode);
    });

 
    Route::group(['namespace' => 'Front', 'prefix' => $currentLanguageCode], function () use($currentLanguageCode) {
        app()->setLocale($currentLanguageCode);
        Route::get('/', 'HomeController@index')->name('home');
        Route::get('getRegionByCity/{id}', 'AjaxController@getRegionByCity');
        Route::get('getAddress/{id}', 'AjaxController@getAddress');
        Route::post('location-suggestions', 'AjaxController@search');
        Route::post('change-location', 'AjaxController@changeLocation');
        Route::get('meal-choices', 'AjaxController@getMealOrSizeChoices');
        Auth::routes();

        Route::get('user-activation-code', 'Auth\RegisterController@showActivationForm')->name('activation');
        Route::post('activateuser', 'Auth\RegisterController@activate_user')->name('activationuser');

        Route::get('edit-user-phone', 'Auth\RegisterController@showEditMobileForm')->name('edit-phone');
        Route::post('edituserphone', 'Auth\RegisterController@EditPhone')->name('editphone');

        Route::get('login/facebook', 'Auth\RegisterController@redirectToProvider')->name('login/facebook');
        Route::get('login/facebook/callback', 'Auth\RegisterController@handleProviderCallback');
        
        Route::get('complete-registeration', 'Auth\RegisterController@showCompleteRegistrationForm')->name('complete_register');
        

        Route::get('about-us', 'StaticController@about_us')->name('about_us');
        Route::get('usage-and-conditions', 'StaticController@usage_coditions')->name('usage_conditions');
        Route::get('terms-and-conditions', 'StaticController@terms_conditions')->name('terms_conditions');
        Route::get('contact-us', 'StaticController@contact_us')->name('contact_us');
        Route::get('offers', 'StaticController@offers')->name('offers');
        Route::post('contact_us', 'StaticController@sendContactMessage')->name('contact');
       
        Route::get('cart', 'CartController@index')->name('showcart');
        Route::get('cart/empty', 'CartController@emptyCart');
        Route::post('cart', 'CartController@store');
        Route::get('resend_order', 'CartController@resendOrder')->name('resend_order');
        Route::get('cart/{index}/remove', 'CartController@remove');
        Route::get('cart/update-quantity', 'CartController@update_quantity');
        Route::get('cart/coupon-check', 'CartController@coupon_check');
        Route::post('cart/new-order', 'CartController@new_order');
        Route::get('resturantes', 'ResturantesController@index')->name('show_resturantes');
        Route::get('near_me', 'ResturantesController@getMyLocation')->name('near_me');
        
        Route::get('resturant/{resturant}', 'ResturantesController@resturant');
        Route::get('resturant/{resturant}/info', 'ResturantesController@resturant_info')->name('resturant_info');
        Route::get('resturant/{resturant}/{menu_section}', 'ResturantesController@menu');
        Route::get('resturant/{resturant}/{menu_section}/{meal}', 'ResturantesController@meal');
        Route::get('resturantes/cuisines/{cuisine}', 'ResturantesController@getResturantesByCuisine');
        Route::post('resturantes/suggest', 'ResturantesController@suggest');
        /*************************** user ***************/
        Route::get('user-profile','UsersController@profile')->name('profile');
        Route::get('edit-user-profile','UsersController@editProfile')->name('edit_profile');
        Route::post('update-user','UsersController@updateProfile')->name('update_user');
        Route::get('add-favourite','UsersController@addDeleteFavourite')->name('add-favourite');
        Route::get('user-favourites','UsersController@favourites')->name('user-favourites');

        /*************************** addresses ************/
        Route::resource('user-addresses', 'AddressesController');
        
        Route::get('delete-addresses/{id}', 'AddressesController@destroy')->name('delete-address');

        /********************** orders *****************/
        Route::resource('user-orders', 'OrdersController');
        Route::post('rate-order', 'OrdersController@rate')->name('rate_order');
        Route::get('order-meal/update-quantity', 'OrdersController@updateOrderMealQuantity');
        Route::get('order-meal/remove', 'OrdersController@removeOrderMeal');
        
        

    });
} else {
    Route::get('/' . $currentLanguageCode, function () use($defaultLanguageCode) {
        return redirect()->to($defaultLanguageCode);
    });
}


//Route::group(['middleware'=>'auth:admin'], function () {
Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function () {
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/error', 'AdminController@error')->name('admin.error');
    Route::get('/change_lang', 'AjaxController@change_lang')->name('ajax.change_lang');
    Route::get('/getRegionByCity/{id}', 'AjaxController@getRegionByCity')->name('ajax.getRegionByCity');
    Route::get('/getResturantBranches/{id}', 'AjaxController@getResturantBranches')->name('ajax.getResturantBranches');
    Route::get('getMenueSectionsByResturant/{id}', 'AjaxController@getMenueSectionsByResturant');
    Route::post('notify', 'AjaxController@notify');
    Route::post('send_email', 'AjaxController@send_email');
    Route::get('getToppings', 'AjaxController@getToppings');
    Route::get('getSizes', 'AjaxController@getSizes');

     Route::get('profile', 'ProfileController@index');
    Route::patch('profile', 'ProfileController@update');



    Route::resource('groups', 'GroupsController');
    Route::resource('admins', 'AdminsController');
    Route::resource('users', 'UsersController');
    Route::resource('categories', 'CategoriesController');
    Route::resource('cities', 'CitiesController');
    Route::resource('sizes', 'SizesController');
    Route::resource('offers', 'OffersController');
    Route::resource('cuisines', 'CuisinesController');
    Route::resource('coupons', 'CouponsController');
    Route::resource('toppings', 'ToppingsController');
    Route::resource('choices', 'ChoicesController');
    Route::resource('sub_choices', 'SubChoicesController');
    Route::resource('meal_sizes', 'MealSizesController');
    Route::resource('resturantes', 'ResturantesController');
    Route::resource('resturant_branches', 'ResturantBranchesController');
    Route::resource('menu_sections', 'MenuSectionsController');
    Route::resource('slider', 'SliderController');
    Route::delete('menu_sections/{id}/toppings', 'MenuSectionsController@destroy_topping');
    Route::resource('meals', 'MealsController');
    Route::delete('meals/{id}/sizes', 'MealsController@destroy_size');
    Route::delete('meals/{id}/toppings', 'MealsController@destroy_topping');
    Route::resource('contact_messages', 'ContactMessagesController');
    Route::resource('recommendations', 'RecommendationsController');
    Route::resource('ads', 'AdsController');
    Route::resource('orders_reports', 'OrdersReportsController');
    Route::post('orders_reports/download', 'OrdersReportsController@download');
    Route::get('settings', 'SettingsController@index');
    Route::get('resturant_menu', 'ResturantMenuController@index');
    Route::get('resturant_meals', 'ResturantMealsController@index');
    Route::get('resturant_meals/{id}', 'ResturantMealsController@show');
    Route::get('resturant_meals/status/{id}', 'ResturantMealsController@status');
    Route::get('resturant_orders', 'ResturantOrdersController@index');
    Route::get('resturant_orders/{id}', 'ResturantOrdersController@show');
    Route::post('change_order_status', 'ResturantOrdersController@changeStatus')->name('order_status');





    Route::patch('settings/{id}', 'SettingsController@update');
    Route::get('notifications', 'NotificationsController@index');
    Route::post('notifications', 'NotificationsController@store');




    Route::post('groups/data', 'GroupsController@data');

    Route::post('admins/data', 'AdminsController@data');
    Route::post('users/data', 'UsersController@data');
    Route::get('users/status/{id}', 'UsersController@status');

    Route::post('contact_messages/data', 'ContactMessagesController@data');
    Route::post('ads/data', 'AdsController@data');
    Route::post('categories/data', 'CategoriesController@data');
    Route::post('cities/data', 'CitiesController@data');
    Route::post('sizes/data', 'SizesController@data');
    Route::post('toppings/data', 'ToppingsController@data');
    Route::post('choices/data', 'ChoicesController@data');
    Route::post('sub_choices/data', 'SubChoicesController@data');
    Route::post('cuisines/data', 'CuisinesController@data');
    Route::post('resturantes/data', 'ResturantesController@data');
    Route::post('resturant_branches/data', 'ResturantBranchesController@data');
    Route::post('menu_sections/data', 'MenuSectionsController@data');
    Route::post('resturant_menu/data', 'ResturantMenuController@data');
    Route::post('resturant_meals/data', 'ResturantMealsController@data');
    Route::post('resturant_orders/data', 'ResturantOrdersController@data');

app/Http/Controllers/Api/AddressesController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\ApiController;
use Illuminate\Http\Request;
use Validator;
use App\Models\Address;

class AddressesController extends ApiController
{
    private $rules = array(
        'city' => 'required',
        'region' => 'required',
        'sub_region' => 'required',
        'street' => 'required',
        'building_number' => 'required',
        'floor_number' => 'required',
        'apartment_number' => 'required',
    );

    public function __construct() {
        parent::__construct();
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $addresses = array();
        try {
            $user = $this->auth_user();
            $addresses = Address::where('user_id',$user->id)
                                  ->paginate($this->limit);

            return _api_json(Address::transformCollection($addresses));
        } catch (\Exception $e) {
            $message = _lang('app.error_is_occured');
            return _api_json($addresses, ['message' => $message],422);
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $validator = Validator::make($request->all(), $this->rules);
            if ($validator->fails()) {
                $errors = $validator->errors()->toArray();
                return _api_json('', ['errors' => $errors],422);
            }
            $user = $this->auth_user();
            $address = new Address;
            $address->city = $request->city;
            $address->region = $request->region;
            $address->sub_region = $request->sub_region;
            $address->street = $request->street;
            $address->building_number = $request->building_number;
            $address->floor_number = $request->floor_number;
            $address->apartment_number = $request->apartment_number;
            if ($request->special_sign) {
                $address->special_sign = $request->special_sign;
            }
            else{
                $address->special_sign = "";
            }
            if ($request->extra_info) {
                $address->extra_info = $request->extra_info;
            }
            else{
                $address->extra_info = "";
            }
            $address->user_id = $user->id;
            $address->save();
            return _api_json('',['message' => _lang('app.added_successfully')]);

        } catch (\Exception $e) {
            $message = _lang('app.error_is_occured');
            return _api_json('', ['message' => $message],422);
        }
    }
   
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $user = $this->auth_user();
            $address = Address::where('id',$id)->where('user_id',$user->id)->first();
            if (!$address) {
                $message = _lang('app.not_found');
                return _api_json('', ['message' => $message], 404);
            }
            $validator = Validator::make($request->all(), $this->rules);
            if ($validator->fails()) {
                $errors = $validator->errors()->toArray();
                return _api_json('', ['errors' => $errors],422);
            }
           
            $address->city = $request->city;
            $address->region = $request->region;
            $address->sub_region = $request->sub_region;
            $address->street = $request->street;
            $address->building_number = $request->building_number;
            $address->floor_number = $request->floor_number;
            $address->apartment_number = $request->apartment_number;
            if ($request->special_sign) {
                $address->special_sign = $request->special_sign;
            }
            if ($request->extra_info) {
                $address->extra_info = $request->extra_info;
            }
            $address->save();
            return _api_json('',['message' => _lang('app.updated_successfully')]);

        } catch (\Exception $e) {
            $message = _lang('app.error_is_occured');
            return _api_json('', ['message' => $message],422);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $user = $this->auth_user();
            $address = Address::where('id',$id)->where('user_id',$user->id)->first();
            if (!$address) {
                $message = _lang('app.not_found');
                return _api_json('', ['message' => $message], 404);
            }
            $address->delete();
            return _api_json('',['message' => _lang('app.deleted_successfully')]);
            
        } catch (\Exception $e) {
            $message = _lang('app.error_is_occured');
            return _api_json('', ['message' => $message],422);
        }
    }
}

resources/views/main_content/front/addresses/create.blade.php
@extends('layouts.user_profile')

@section('pageTitle',$page_title)


@section('title')
  {{ $page_title }}
@endsection
@section('js')
	<script src=" {{ url('public/front/scripts') }}/addresses.js"></script>
@endsection


@section('content')


<form action="{{ route('user-addresses.store') }}" method="post" class="form-uecl" id="addEditAddress">



	{{ csrf_field() }}
	<div class="row">
		<input type="hidden" name="id" value="0" id="id">
		<div class="col-sm-12 input">
			<div class="row form-group">
				<label class="col-sm-4 control-label"> {{ _lang('app.city') }} </label>
				<div class="col-sm-8">
					<input type="text" name="city" class="form-control" placeholder="" value="" id="city">
				</div>
				 <span class="help-block">
		             @if ($errors->has('city'))
		                {{ $errors->first('city') }}
		              @endif
		         </span>
			</div>
		</div>
		<!--input-->

		<div class="col-sm-12 input">
			<div class="row form-group">
				<label class="col-sm-4 control-label">{{ _lang('app.region') }} </label>
				<div class="col-sm-8">
					<input type="text" name="region" class="form-control" placeholder="" value="" id="region">
				</div>
				<span class="help-block">
		             @if ($errors->has('region'))
		                {{ $errors->first('region') }}
		              @endif
		         </span>
			</div>
		</div>
		<!--input-->

		<div class="col-sm-12 input">
			<div class="row form-group">
				<label class="col-sm-4 control-label"> {{ _lang('app.sub_region') }} </label>
				<div class="col-sm-8">
					<input type="text" name="sub_region" class="form-control" placeholder="" value="" id="sub_region">
				</div>
				<span class="help-block">
		             @if ($errors->has('sub_region'))
		                {{ $errors->first('sub_region') }}
		              @endif
		         </span>
			</div>
		</div>
		<!--input-->

		<div class="col-sm-12 input">
			<div class="row form-group">
				<label class="col-sm-4 control-label"> {{ _lang('app.street') }} </label>
				<div class="col-sm-8">
					<input type="text" name="street" class="form-control" placeholder="" value="" id="street">
				</div>
				<span class="help-block">
		             @if ($errors->has('street'))
		                {{ $errors->first('street') }}
		              @endif
		        </span>
			</div>
		</div>
		<!--input--> 

		<div class="col-sm-12 input">
			<div class="row form-group">
				<label class="col-sm-4 control-label"> {{ _lang('app.building_number') }} </label>
				<div class="col-sm-8">
					<input type="text" name="building_number" class="form-control" placeholder="" value="" id="building_number">
				</div>
				<span class="help-block">
		             @if ($errors->has('building_number'))
		                {{ $errors->first('building_number') }}
		              @endif
		        </span>
			</div>
		</div>
		<!--input--> 


		<div class="col-sm-12 input">
			<div class="row form-group">
				<label class="col-sm-4 control-label"> {{ _lang('app.floor_number') }} </label>
				<div class="col-sm-8">
					<input type="text" name="floor_number" class="form-control" placeholder="" value="" id="floor_number">
				</div>
				<span class="help-block">
		             @if ($errors->has('floor_number'))
		                {{ $errors->first('floor_number') }}
		              @endif
		        </span>
			</div>
		</div>
		<!--input--> 

		<div class="col-sm-12 input">
			<div class="row form-group">
				<label class="col-sm-4 control-label"> {{ _lang('app.apartment_number') }} </label>
				<div class="col-sm-8">
					<input type="text" name="apartment_number" class="form-control" placeholder="" value="" id="apartment_number">
				</div>
				<span class="help-block">
		             @if ($errors->has('apartment_number'))
		                {{ $errors->first('apartment_number') }}
		              @endif
		        </span>
			</div>
		</div>
		<!--input--> 

		<div class="col-sm-12 input">
			<div class="row form-group">
				<label class="col-sm-4 control-label"> {{ _lang('app.special_sign') }} </label>
				<div class="col-sm-8">
					<input type="text" name="special_sign" class="form-control" placeholder="" value="">
				</div>
				<span class="help-block">
		             @if ($errors->has('special_sign'))
		                {{ $errors->first('special_sign') }}
		              @endif
		        </span>
			</div>
		</div>
		<!--input--> 


		<div class="col-sm-12 input">
			<div class="row form-group">
				<label class="col-sm-4 control-label"> {{ _lang('app.extra_info') }} </label>
				<div class="col-sm-8">
					<textarea name="extra_info" class="form-control textarea"></textarea>
				</div>
				<span class="help-block">
		             @if ($errors->has('extra_info'))
		                {{ $errors->first('extra_info') }}
		              @endif
		        </span>
			</div>
		</div>
		<!--input--> 

		


		<div class="col-sm-8 input col-sm-offset-4">
			<button class="botoom submit-form" type="submit"> {{ _lang('app.save') }}</button>
		</div>
	</div>
</form>
@endsection

resources/views/main_content/front/addresses/edit.blade.php
@extends('layouts.user_profile')

@section('pageTitle',$page_title)

@section('title')
  {{ $page_title }}
@endsection

@section('js')
<script src=" {{ url('public/front/scripts') }}/addresses.js"></script>
@endsection


@section('content')



<form action="{{ route('user-addresses.update',Crypt::encrypt($address->id)) }}" method="post" class="form-uecl" id="addEditAddress">

	{{ csrf_field() }}
	<div class="row">
	<input type="hidden" name="id" id="id" value="{{ $address->id }}">
		<div class="col-sm-12 input">
			<div class="row form-group">
				<label class="col-sm-4 control-label"> {{ _lang('app.city') }} </label>
				<div class="col-sm-8">
					<input type="text" name="city" class="form-control" placeholder="" value="{{ $address->city }}" id="city">
				</div>
				 <span class="help-block">
		             @if ($errors->has('city'))
		                {{ $errors->first('city') }}
		              @endif
		         </span>
			</div>
		</div>
		<!--input-->

		<div class="col-sm-12 input">
			<div class="row form-group">
				<label class="col-sm-4 control-label">{{ _lang('app.region') }} </label>
				<div class="col-sm-8">
					<input type="text" name="region" class="form-control" placeholder="" value="{{ $address->region }}" id="region">
				</div>
				<span class="help-block">
		             @if ($errors->has('region'))
		                {{ $errors->first('region') }}
		              @endif
		         </span>
			</div>
		</div>
		<!--input-->

		<div class="col-sm-12 input">
			<div class="row form-group">
				<label class="col-sm-4 control-label"> {{ _lang('app.sub_region') }} </label>
				<div class="col-sm-8">
					<input type="text" name="sub_region" class="form-control" placeholder="" value="{{ $address->sub_region }}" id="sub_region">
				</div>
				<span class="help-block">
		             @if ($errors->has('sub_region'))
		                {{ $errors->first('sub_region') }}
		              @endif
		         </span>
			</div>
		</div>
		<!--input-->

		<div class="col-sm-12 input">
			<div class="row form-group">
				<label class="col-sm-4 control-label"> {{ _lang('app.street') }} </label>
				<div class="col-sm-8">
					<input type="text" name="street" class="form-control" placeholder="" value="{{ $address->street }}" id="street">
				</div>
				<span class="help-block">
		             @if ($errors->has('street'))
		                {{ $errors->first('street') }}
		              @endif
		        </span>
			</div>
		</div>
		<!--input--> 

		<div class="col-sm-12 input">
			<div class="row form-group">
				<label class="col-sm-4 control-label"> {{ _lang('app.building_number') }} </label>
				<div class="col-sm-8">
					<input type="text" name="building_number" class="form-control" placeholder="" value="{{ $address->building_number }}" id="building_number">
				</div>
				<span class="help-block">
		             @if ($errors->has('building_number'))
		                {{ $errors->first('building_number') }}
		              @endif
		        </span>
			</div>
		</div>
		<!--input--> 


		<div class="col-sm-12 input">
			<div class="row form-group">
				<label class="col-sm-4 control-label"> {{ _lang('app.floor_number') }} </label>
				<div class="col-sm-8">
					<input type="text" name="floor_number" class="form-control" placeholder="" value="{{ $address->floor_number }}" id="floor_number">
				</div>
				<span class="help-block">
		             @if ($errors->has('floor_number'))
		                {{ $errors->first('floor_number') }}
		              @endif
		        </span>
			</div>
		</div>
		<!--input--> 

		<div class="col-sm-12 input">
			<div class="row form-group">
				<label class="col-sm-4 control-label"> {{ _lang('app.apartment_number') }} </label>
				<div class="col-sm-8">
					<input type="text" name="apartment_number" class="form-control" placeholder="" value="{{ $address->apartment_number }}" id="apartment_number">
				</div>
				<span class="help-block">
		             @if ($errors->has('apartment_number'))
		                {{ $errors->first('apartment_number') }}
		              @endif
		        </span>
			</div>
		</div>
		<!--input--> 

		<div class="col-sm-12 input">
			<div class="row form-group">
				<label class="col-sm-4 control-label"> {{ _lang('app.special_sign') }} </label>
				<div class="col-sm-8">
					<input type="text" name="special_sign" class="form-control" placeholder="" value="{{ $address->special_sign }}">
				</div>
				<span class="help-block">
		             @if ($errors->has('special_sign'))
		                {{ $errors->first('special_sign') }}
		              @endif
		        </span>
			</div>
		</div>
		<!--input--> 


		<div class="col-sm-12 input">
			<div class="row form-group">
				<label class="col-sm-4 control-label"> {{ _lang('app.extra_info') }} </label>
				<div class="col-sm-8">
					<textarea name="extra_info" class="form-control textarea">{{ $address->extra_info }}</textarea>
				</div>
				<span class="help-block">
		             @if ($errors->has('extra_info'))
		                {{ $errors->first('extra_info') }}
		              @endif
		        </span>
			</div>
		</div>
		<!--input--> 

		


		<div class="col-sm-8 input col-sm-offset-4">
			<button class="botoom submit-form" type="submit"> {{ _lang('app.save') }}</button>
		</div>
	</div>
</form>
@endsection

resources/views/main_content/front/addresses/index.blade.php
@extends('layouts.user_profile')
@section('pageTitle',$page_title)

@section('title')
  {{ $page_title }}
@endsection
@section('js')
	<script>
		
         $('#confirm-delete').on('show.bs.modal', function (e) {
            $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));
        });

	</script>

<script type="text/javascript" src="{{url('public/front/js')}}/jquery.jscroll.js"></script>

<script type="text/javascript">
    $('ul.pagination').hide();
    $(function () {
        $('.infinite-scroll').jscroll({
            autoTrigger: true,
            loadingHtml: '<img class="center-block" style="margin-left:35%;" src="{{url('public/front')}}/images/loading.gif" alt="Loading..." />',
            padding: 0,
            nextSelector: '.pagination li.active + li a',
            contentSelector: 'div.infinite-scroll',
            callback: function () {
                $('ul.pagination').remove();
            }
        });
    });
</script>
@endsection

@section('content')
	<a href="{{ route('user-addresses.create') }}" class="botoom addadrs"><i class="fa fa-plus" aria-hidden="true"></i>{{ _lang('app.add_address') }}</a>
         <div class="infinite-scroll">
         @foreach ($addresses as $address)
         	<div class="agent"> 

			<a href="#confirm-delete" data-href="{{ route('delete-address',Crypt::encrypt($address->id)) }}" title="{{ _lang('app.delete') }}" data-toggle="modal" class="fa fa-times telibnk"></a>

			 <a href="{{ route('user-addresses.edit',Crypt::encrypt($address->id)) }}" title="{{ _lang('app.edit') }}" class="fa fa-pencil telibnk"></a>

				<div class="col-sm-12 titleagent">

				  <h3 class="nam-tit">{{ $address->city }} - {{ $address->region }}</h3>


				  <p class="textblog">{{ $address->city }} - {{ $address->region }} - {{ $address->sub_region }} - {{ $address->street }}</p>

				</div>
				<!--titleagent--> 
				
		    </div>
         @endforeach
         {{ $addresses->links() }}
      </div>

<div id="confirm-delete" class="modal fade"  tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog"> 
    
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title titlpop">هل انت متأكد من الحذف</h4>
      </div>
      <div class="modal-footer textcent">
        <button type="button" class="btn btn-default" data-dismiss="modal">{{ _lang('app.cancel') }}</button>
        <a class="btn btn-danger btn-ok">{{ trans('messages.delete') }}</a>
      </div>
    </div>
  </div>
</div>

<div class="clearfix"></div>

		
@endsection